### ISSUE TITLE
Crash: java.lang.NumberFormatException in StatsSqlUtils

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-FluxC-Android#1073]
First crashed in 11.5-rc-1

```
Caused by java.lang.NumberFormatException: Invalid number: Jan 
       at com.google.gson.internal.bind.util.ISO8601Utils.parseInt(ISO8601Utils.java:311)
       at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:129)
       at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:85)
       at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:75)
       at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:46)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson(Gson.java:927)
       at com.google.gson.Gson.fromJson(Gson.java:892)
       at com.google.gson.Gson.fromJson(Gson.java:841)
       at com.google.gson.Gson.fromJson(Gson.java:813)
       at org.wordpress.android.fluxc.persistence.StatsSqlUtils.select(StatsSqlUtils.kt:53)
       at org.wordpress.android.fluxc.persistence.StatsSqlUtils.select$default(StatsSqlUtils.kt:43)
       at org.wordpress.android.fluxc.persistence.InsightsSqlUtils.select(InsightsSqlUtils.kt:118)
       at org.wordpress.android.fluxc.persistence.InsightsSqlUtils.selectLatestPostDetail(InsightsSqlUtils.kt:79)
       at org.wordpress.android.fluxc.store.InsightsStore.getLatestPostInsights(InsightsStore.kt:100)
       at org.wordpress.android.ui.stats.refresh.lists.sections.insights.usecases.LatestPostSummaryUseCase.loadCachedData(LatestPostSummaryUseCase.kt:36)
       at org.wordpress.android.ui.stats.refresh.lists.sections.BaseStatsUseCase.fetch(BaseStatsUseCase.kt:53)
       at org.wordpress.android.ui.stats.refresh.lists.sections.BaseStatsUseCase$fetch$1.doResume(Unknown Source:15)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
       at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
       at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
       at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

5c1f17c4f8b88c2963e80681-fabric

**Comment by jtreanor** [comment]
I have confirmed this is no longer happening as of 11.6.
