### ISSUE TITLE
WC: Crash retrieving product image when product has no image

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#1153]
Attempting to retrieve a product's image when the product has no images causes the crash below:

```
Process: com.woocommerce.android, PID: 3061
    java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at org.wordpress.android.fluxc.model.WCProductModel.getFirstImage(WCProductModel.kt:159)
        at com.woocommerce.android.tools.ProductImageMap.get(ProductImageMap.kt:36)
        at com.woocommerce.android.ui.orders.OrderDetailProductListView$ProductListAdapter.onBindViewHolder(OrderDetailProductListView.kt:140)
        at com.woocommerce.android.ui.orders.OrderDetailProductListView$ProductListAdapter.onBindViewHolder(OrderDetailProductListView.kt:123)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
```

**Comment by nbradbury** [comment]
Closing this as it has already been fixed (just need to use a more recent FluxC hash in WCAndroid).
