### ISSUE TITLE
Crash: New NullPointerException crashes in AccountRestClient appeared in past 24 hours

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-FluxC-Android#1170]
Two new `NullPointerException` crashes that had not happened before suddenly became widespread in the past 24 hours. They are happening on versions as far back as 10.2.

Here is the first crash (more common, 424 times so far):

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'long org.wordpress.android.fluxc.network.rest.wpcom.account.AccountResponse.ID' on a null object reference
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient.responseToAccountModel(AccountRestClient.java:1076)
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient.access$000(AccountRestClient.java:66)
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient$1.onResponse(AccountRestClient.java:219)
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient$1.onResponse(AccountRestClient.java:216)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:52)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6364)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

5bbe4d54f8b88c29635e0f87-fabric

And the other one (169 times so far):

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.wordpress.android.fluxc.network.rest.wpcom.account.AccountSettingsResponse.user_login' on a null object reference
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient.responseToAccountSettingsModel(AccountRestClient.java:1093)
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient.access$300(AccountRestClient.java:66)
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient$3.onResponse(AccountRestClient.java:246)
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient$3.onResponse(AccountRestClient.java:243)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:53)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

5bbe4d83f8b88c29635e142c-fabric

**Comment by jtreanor** [comment]
This appears to be another related crash:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.Map org.wordpress.android.fluxc.network.rest.wpcom.site.PostFormatsResponse.formats' on a null object reference
       at org.wordpress.android.fluxc.network.rest.wpcom.site.SiteRestClient$7.onResponse(SiteRestClient.java:265)
       at org.wordpress.android.fluxc.network.rest.wpcom.site.SiteRestClient$7.onResponse(SiteRestClient.java:261)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:53)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

5c890414f8b88c2963f324e1-fabric

**Comment by jtreanor** [comment]
Interestingly, all of these crashes occurred between 13:17 UTC and 13:26 UTC yesterday (March 13th). There have been no crashes since then.

It looks like there may have been some API issues in this period. I'm digging into to see if I can find anything that lines up.

**Comment by jtreanor** [comment]
Okay, so it turns out this was a known incident with the API. A breaking change was made and quickly reverted.

Would it be good to be more resilient to API issues like these or does it make sense to just close this?

**Comment by jtreanor** [comment]
After discussion with the team, we have decided that making the clients resilient to significant API failures like these could pose a risk of us missing major issues.

For that reason, I am closing this as there is no more action to be taken.
