### ISSUE TITLE
Woo: IllegalStateException Not a JSON Object: "failed"

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#1331]
User is experiencing a crash every time they switch to the orders tab, apparently due to invalid JSON in the response for the shipment provider list.

```
java.lang.IllegalStateException: Not a JSON Object: "failed"
    at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
    at org.wordpress.android.fluxc.network.rest.wpcom.wc.order.OrderRestClient.jsonResponseToShipmentProviderList(OrderRestClient.kt:725)
    at org.wordpress.android.fluxc.network.rest.wpcom.wc.order.OrderRestClient.access$jsonResponseToShipmentProviderList(OrderRestClient.kt:49)
    at org.wordpress.android.fluxc.network.rest.wpcom.wc.order.OrderRestClient$fetchOrderShipmentProviders$request$1.invoke(OrderRestClient.kt:595)
    at org.wordpress.android.fluxc.network.rest.wpcom.wc.order.OrderRestClient$fetchOrderShipmentProviders$request$1.invoke(OrderRestClient.kt:49)
    at org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelGsonRequest$buildGetRequest$wrappedListener$1.onResponse(JetpackTunnelGsonRequest.kt:118)
    at org.wordpress.android.fluxc.network.rest.wpcom.jetpacktunnel.JetpackTunnelGsonRequest$buildGetRequest$wrappedListener$1.onResponse(JetpackTunnelGsonRequest.kt:89)
    at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:53)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

[Relevant Sentry link](https://sentry.io/organizations/a8c/issues/1140272336/?environment=release&project=1459556&query=is%3Aunresolved&statsPeriod=7d)

**Comment by zwiesman31** [comment]
2246217-zen is the ticket, for reference. :)

**Comment by nbradbury** [comment]
Crash happens [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/27cb1933cda00240a63159b88fc17267ff449fd4/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt#L725). Looks like `countryEntry.value` is simply `failed`.
