### ISSUE TITLE
XMLRPC and REST clients must accept any kind of invalid responses and not crash

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#134]
We should add new tests with invalid responses.

Example of crashing client:

```
java.lang.NumberFormatException: Invalid long: "false"
    at java.lang.Long.invalidLong(Long.java:124)
    at java.lang.Long.parse(Long.java:363)
    at java.lang.Long.parseLong(Long.java:353)
    at java.lang.Long.parseLong(Long.java:321)
    at java.lang.Long.valueOf(Long.java:511)
    at org.wordpress.android.fluxc.network.xmlrpc.site.SiteXMLRPCClient.updateSiteFromOptions(SiteXMLRPCClient.java:182)
    at org.wordpress.android.fluxc.network.xmlrpc.site.SiteXMLRPCClient.access$400(SiteXMLRPCClient.java:30)
    at org.wordpress.android.fluxc.network.xmlrpc.site.SiteXMLRPCClient$3.onResponse(SiteXMLRPCClient.java:92)
    at org.wordpress.android.fluxc.network.xmlrpc.XMLRPCRequest.deliverResponse(XMLRPCRequest.java:51)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
```

**Comment by aforcier** [comment]
Related: https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/80
