### ISSUE TITLE
IndexOutOfBoundsException in PostSqlUtils.insertOrUpdatePost

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1524]
It looks like we end up removing all posts from the `postResult` [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PostSqlUtils.java#L86).

@malinajirka Do you think you can have a look at this one? I don't think we were expecting for all post results to have the same post id, so I am guessing the solution will be to make sure we still have at least one post left after the loop. However, I don't have the full picture about the race condition we are dealing there, so it might be best if you took a look at it.

_P.S: We currently have 2.2k crashes for 221 users about this. I am not sure how it slipped through the cracks._

https://sentry.io/share/issue/9a8d493b2b0a4dbdaf859debb00ac81c/

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.get(ArrayList.java:437)
    at org.wordpress.android.fluxc.persistence.PostSqlUtils.insertOrUpdatePost(PostSqlUtils.java:88)
    at org.wordpress.android.fluxc.persistence.PostSqlUtils.insertOrUpdatePostKeepingLocalChanges(PostSqlUtils.java:99)
    at org.wordpress.android.fluxc.store.PostStore.handleFetchPostsCompleted(PostStore.java:858)
    at org.wordpress.android.fluxc.store.PostStore.onAction(PostStore.java:593)
```

**Comment by malinajirka** [comment]
I'll look into it next week during my groundskeeping rotation. Since the code freeze is today it shouldn't affect the target version.
