### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'void org.wordpress.android.fluxc.network.BaseRequest$OnParseE...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1565]
**Sentry Url**: https://sentry.io/share/issue/b6e3a784cf1b4fbbaceeee0019ac6427/
**User Count**: 240
**Count**: 2477
**First Release**: org.wordpress.android-12.3.1
**First Seen**: 2019-05-08T16:50:41Z
**Last Seen**: 2020-04-24T20:06:01Z
**24 Hours**: 8
**30 Days**: 483

```
NullPointerException: Attempt to invoke interface method 'void org.wordpress.android.fluxc.network.BaseRequest$OnParseErrorListener.onParseError(org.wordpress.android.fluxc.utils.ErrorUtils$OnUnexpectedError)' on a null object reference
     at org.wordpress.android.fluxc.network.BaseRequest.deliverError(BaseRequest.java:332)
     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
     at android.os.Handler.handleCallback(Handler.java:836)
     at android.os.Handler.dispatchMessage(Handler.java:103)
     at android.os.Looper.loop(Looper.java:203)
     at android.app.ActivityThread.main(ActivityThread.java:6251)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by bummytime** [comment]
@maxme So quickly investigating this NPE, based on the sentry logs this seems to be a `MalformedJsonException` after closing the app. 

Any insights you could provide on this?

**Comment by maxme** [comment]
I had a quick look, it seems we have an optional listener that is not treated as optional. I can do a quick fix for that one.
