### ISSUE TITLE
IllegalStateException: site.wpApiRestUrl must not be null

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1594]
**Sentry Url**: https://sentry.io/share/issue/fac21421243d44ee9ddb6127e35d7f12/
**User Count**: 143
**Count**: 391
**First Release**: org.wordpress.android-14.7-rc-2
**First Seen**: 2020-04-28T06:06:23Z
**Last Seen**: 2020-05-27T09:36:58Z
**24 Hours**: 5
**30 Days**: 395

```
IllegalStateException: site.wpApiRestUrl must not be null
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:93)
     at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:133)
     at org.wordpress.android.fluxc.store.ReactNativeStore$executeWPAPIRequest$2.invokeSuspend(null:12)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

**Comment by maxme** [comment]
This seems to be a duplicate of https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1579

**Comment by oguzkocer** [comment]
Thanks @maxme! I merged the two issues in Sentry and updated the original issue's url. They have different enough stacktraces that they didn't show up in their "similar issues" section, so I missed it.
