### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.plugins.Plu...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1616]
**Sentry Url**: https://sentry.io/share/issue/6236454478fb49f9a478eb4848e4fb4f/
**User Count**: 34
**Count**: 552
**First Release**: org.wordpress.android-12.4
**First Seen**: 2019-05-13T16:48:35Z
**Last Seen**: 2020-06-23T18:27:08Z
**24 Hours**: 10
**30 Days**: 104

```
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.plugins.PluginBrowserActivity}: android.database.sqlite.SQLiteException: too many SQL variables (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT * FROM WPOrgPluginModel WHERE (SLUG IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?...
     at org.wordpress.android.fluxc.persistence.PluginSqlUtils.getWPOrgPluginsForDirectory(PluginSqlUtils.java:121)
     at org.wordpress.android.fluxc.store.PluginStore.getPluginDirectory(PluginStore.java:626)
     at org.wordpress.android.viewmodel.plugins.PluginBrowserViewModel.updateListStateToReady(PluginBrowserViewModel.kt:402)
     at org.wordpress.android.viewmodel.plugins.PluginBrowserViewModel.start(PluginBrowserViewModel.kt:153)
     at org.wordpress.android.ui.plugins.PluginBrowserActivity.onCreate(PluginBrowserActivity.java:107)
...
(23 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Adding to Groundskeeping
