### ISSUE TITLE
AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1627]
**Sentry Url**: https://sentry.io/share/issue/d8b886035d87475996696ee37471cb03/
**User Count**: 20
**Count**: 20
**First Release**: org.wordpress.android@15.1+885
**First Seen**: 2020-06-30T19:24:35.690000Z
**Last Seen**: 2020-07-03T01:24:34Z
**24 Hours**: 10
**30 Days**: 20

```
AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT
     at org.wordpress.android.fluxc.store.stats.time.VisitsAndViewsStore$fetchVisits$2.invokeSuspend(VisitsAndViewsStore.kt:44)
     at org.wordpress.android.fluxc.store.stats.time.VisitsAndViewsStore$fetchVisits$2.invoke(null:10)
     at org.wordpress.android.fluxc.tools.CoroutineEngine.withDefaultContext(CoroutineEngine.kt:27)
     at org.wordpress.android.fluxc.store.stats.time.VisitsAndViewsStore.fetchVisits(VisitsAndViewsStore.kt:38)
     at org.wordpress.android.ui.stats.refresh.lists.sections.granular.usecases.OverviewUseCase.fetchRemoteData(OverviewUseCase.kt:77)
     at org.wordpress.android.ui.stats.refresh.lists.sections.BaseStatsUseCase.fetch(BaseStatsUseCase.kt:76)
     at org.wordpress.android.ui.stats.refresh.lists.BaseListUseCase$loadData$3$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(BaseListUseCase.kt:119)
...
(14 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@planarvoid this may be related to #1604 fix (the first occurrence was Jun 30, 2020). Can you take a peek at this?

**Comment by planarvoid** [comment]
This seems to be caused by a [bug in Android](https://github.com/mixpanel/mixpanel-android/issues/567). It's rarely crashing when you call `Date.toString` method. It's related to the changes you mentioned @bummytime . It seems that the only solution is to [catch the exception](https://stackoverflow.com/questions/51453091/android-facebook-sdk-internal-utility-java-lang-assertionerror/52035884#52035884) so I'll do just that 👍

**Comment by bummytime** [comment]
Thank you @planarvoid 🙇‍♂️
