### ISSUE TITLE
JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $[0]

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#1644]
This is a very recent issue and it's been happening a lot for a small number of users. cc @mchowning @chipsnyder 

**Sentry Url**: https://sentry.io/share/issue/0af0bb097b7a4d899fd61567c4707ea2/
**User Count**: 7
**Count**: 830
**First Release**: org.wordpress.android@15.2+890
**First Seen**: 2020-07-15T22:42:22.444000Z
**Last Seen**: 2020-07-29T12:41:09Z
**24 Hours**: 21
**30 Days**: 830

```
JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $[0]
     at org.wordpress.android.fluxc.model.EditorThemeElementListSerializer.deserialize(EditorTheme.kt:107)
     at org.wordpress.android.fluxc.model.EditorThemeElementListSerializer.deserialize(EditorTheme.kt:99)
     at org.wordpress.android.fluxc.store.EditorThemeStore.handleFetchEditorTheme(EditorThemeStore.kt:83)
     at org.wordpress.android.fluxc.store.EditorThemeStore$handleFetchEditorTheme$1.invokeSuspend(null:12)
...
(21 additional frame(s) were not displayed)
```

**Comment by chipsnyder** [comment]
I was able to recreate this issue by setting the theme up with

```
add_theme_support( 'editor-gradient-presets', array(array()));
```

or 

```
add_theme_support( 'editor-color-palette', array(array()));
```

Which would be an invalid theme configuration but now that we tracked this down I can open a PR to get it fixed.

**Comment by chipsnyder** [comment]
PR's are open for this now.
