### ISSUE TITLE
Woo: IllegalStateException in WCProductVariationModel

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#1862]
```
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
        at org.wordpress.android.fluxc.model.WCProductVariationModel.getImageModel(WCProductVariationModel.kt:98)
        at com.woocommerce.android.model.ProductVariationKt.toAppModel(ProductVariation.kt:162)
```

**Comment by nbradbury** [comment]
False alarm, the crash is elsewhere further down the log.
