### ISSUE TITLE
Crash when refreshing the Post List on a jetpack site

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#286]
Looks like a long vs int issue:

```
01-23 03:10:21.687 25699-25699/org.wordpress.android.beta E/WordPress-API: Volley error
 com.android.volley.ParseError: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 42949672967 at line 1 column 39 path $.posts[0].ID
     at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:71)
     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
  Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 42949672967 at line 1 column 39 path $.posts[0].ID
     at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
     at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
     at com.google.gson.Gson.fromJson(Gson.java:879)
     at com.google.gson.Gson.fromJson(Gson.java:844)
     at com.google.gson.Gson.fromJson(Gson.java:793)
     at com.google.gson.Gson.fromJson(Gson.java:765)
     at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:67)
     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125) 
  Caused by: java.lang.NumberFormatException: Expected an int but was 42949672967 at line 1 column 39 path $.posts[0].ID
     at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
     at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
```

**Comment by aforcier** [comment]
Fixed in #287.
