### ISSUE TITLE
Crashlytics report 7.0-rc-1: Malformed JSON response

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#362]
```
Non-fatal Exception: com.android.volley.ParseError: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3409 path $
       at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:71)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
Caused by com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3409 path $
       at com.google.gson.Gson.assertFullConsumption(Gson.java:855)
       at com.google.gson.Gson.fromJson(Gson.java:845)
       at com.google.gson.Gson.fromJson(Gson.java:793)
       at com.google.gson.Gson.fromJson(Gson.java:765)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:67)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
Caused by com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3409 path $
       at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
       at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1416)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
       at com.google.gson.Gson.assertFullConsumption(Gson.java:851)
       at com.google.gson.Gson.fromJson(Gson.java:845)
       at com.google.gson.Gson.fromJson(Gson.java:793)
       at com.google.gson.Gson.fromJson(Gson.java:765)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:67)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:125)
```

**Comment by oguzkocer** [comment]
Closed by #365
