### ISSUE TITLE
Timeout issues uploading media

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-FluxC-Android#370]
As reported in wp-android here https://github.com/wordpress-mobile/WordPress-Android/issues/5409#issuecomment-287333185 I'm having issue uploading media on WordPress.com. 

```
java.net.SocketTimeoutException: Read timed out 
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
```

The problem is with the Read timeout, that reaches the limit (without a valid reason) when uploading a "big" (>3MB) media file to the server. The size of the picture could vary, since I can reproduce the issue constantly on Android 7.1.1 with a 3MB file, but on another device with Android 5 I need to use pictures that are >5MB in size. Anyway the description of the issue I left on wp-android does have all the details.

A quick and partial solution to this issue would be to raise the default_read_timeout to 60 seconds in `MediaRestClient`. 
Note: Socket timeout in the old version of our networking layer was set 60 secs.

**Comment by daniloercoli** [comment]
Sounds similar (but on the old network stack) - https://android.forums.wordpress.org/topic/uploading-19mb-photo-gives-read-timed-out
