### ISSUE TITLE
Crash report 7.0-rc-4: Unique site constraint

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#397]
We should probably convert this into a `DuplicateSiteException`.
```
Caused by android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: SiteModel.SITE_ID, SiteModel.URL (Sqlite code 2067), (OS error - 2:No such file or directory)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:742)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1627)
       at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1568)
       at com.yarolegovich.wellsql.UpdateQuery.execute(UpdateQuery.java:79)
       at org.wordpress.android.fluxc.persistence.SiteSqlUtils.insertOrUpdateSite(SiteSqlUtils.java:139)
       at org.wordpress.android.fluxc.store.SiteStore.updateSite(SiteStore.java:745)
       at org.wordpress.android.fluxc.store.SiteStore.onAction(SiteStore.java:612)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:833)
```

**Comment by maxme** [comment]
This can happen in the current situation:

* User adds a self hosted site: url: "pony.com", id: "1"
* `wp.getOption` is called and the response has an incorrect site url, url: "", id: "1"
* User adds a second self host site: url: "horse.com", id: "1"
* Everything works, url and id are different
* `wp.getOption` is called on the second site and the response has an incorrect site url (again), url: "", id: "1"
* Oh no, it's already in there -> :boom:
