### ISSUE TITLE
Crash WPAndroid 7.1 - SiteStore$NewSitePayload.siteName' on a null object reference

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-FluxC-Android#412]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.wordpress.android.fluxc.store.SiteStore$NewSitePayload.siteName' on a null object reference
       at org.wordpress.android.fluxc.store.SiteStore.createNewSite(SiteStore.java:685)
       at org.wordpress.android.fluxc.store.SiteStore.onAction(SiteStore.java:639)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by maxme** [comment]
We got a null Payload here, it's a wpandroid issue. It should be easy to track, it's either in the new user or new site screen.
