### ISSUE TITLE
Crash - SiteRestClient attempt to read from null object

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-FluxC-Android#465]
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.wordpress.android.fluxc.network.rest.wpcom.site.SiteWPComRestResponse$SitesResponse.sites' on a null object reference
       at org.wordpress.android.fluxc.network.rest.wpcom.site.SiteRestClient$1.onResponse(SiteRestClient.java:97)
       at org.wordpress.android.fluxc.network.rest.wpcom.site.SiteRestClient$1.onResponse(SiteRestClient.java:92)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:50)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by aforcier** [comment]
I can reproduce this by simulating an empty server response to `/me/sites/`. It's odd though, since we should either get an error or, in the case of no-site WP.com users, an empty list:

```json
{
  "sites": []
}
```

The crash seems only to have affected one user - I would guess it's something local to their network setup rather than a WP.com API issue. I think we can throw an `INVALID_RESPONSE` error instead of crashing, and move on.
