### ISSUE TITLE
Crash - Deleting posts with attached media

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-FluxC-Android#585]
I got a crash while deleting a post that had media uploading in it.

```
10-19 15:26:12.873 24811-31747/org.wordpress.android E/SQLiteLog: (787) abort at 19 in [INSERT INTO PostUploadModel(UPLOAD_STATE,ERROR_MESSAGE,_id,ASSOCIATED_MEDIA_IDS,ERROR_TYPE) VALUES (?,?,?,?,?)]: FOREIGN KEY constraint failed
10-19 15:26:12.875 24811-31747/org.wordpress.android E/SQLiteDatabase: Error inserting UPLOAD_STATE=2 ERROR_MESSAGE=null _id=100 ASSOCIATED_MEDIA_IDS=74,75,76,77,78,79,80 ERROR_TYPE=null
 android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
 at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
 at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
 at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
 at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
 at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
 at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
 at com.yarolegovich.wellsql.InsertQuery.execute(InsertQuery.java:61)
 at org.wordpress.android.fluxc.persistence.UploadSqlUtils.insertOrUpdatePost(UploadSqlUtils.java:136)
 at org.wordpress.android.fluxc.store.UploadStore.cancelPost(UploadStore.java:440)
 at org.wordpress.android.fluxc.store.UploadStore.handleCancelMedia(UploadStore.java:326)
 at org.wordpress.android.fluxc.store.UploadStore.onMediaAction(UploadStore.java:128)
 at org.wordpress.android.fluxc.store.UploadStore.onAction(UploadStore.java:98)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
 at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
 at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:818)
```

**Comment by aforcier** [comment]
@daniloercoli I'm a bit surprised by this, as `FOREIGN KEY constraint failed` isn't supposed to cause a crash (see for example https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/533#issuecomment-327235683). Was there maybe another stack trace below this showing something else?

**Comment by daniloercoli** [comment]
🤦‍♂️ You're right. I've missed something below that made the app crashing. Closing this ticket.
