### ISSUE TITLE
Crash report 8.8-rc-2: NPE in AccountRestClient

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#618]
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'byte[] com.android.volley.NetworkResponse.data' on a null object reference
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient$AccountPushSocialResponsePayload.<init>(AccountRestClient.java:77)
       at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient$14.onErrorResponse(AccountRestClient.java:371)
       at org.wordpress.android.fluxc.network.BaseRequest.deliverError(BaseRequest.java:244)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/5a0d417361b02d480d89d10f

**Comment by aforcier** [comment]
Fixed in #620.
