### ISSUE TITLE
Crash in SiteXMLRPCClient when getting jetpack_client_id

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#80]
```
FATAL EXCEPTION: main
	Process: org.wordpress.android.stores.example, PID: 2731
	java.lang.NumberFormatException: Invalid long: "null"
		at java.lang.Long.invalidLong(Long.java:124)
		at java.lang.Long.parseLong(Long.java:345)
		at java.lang.Long.parseLong(Long.java:321)
		at java.lang.Long.valueOf(Long.java:511)
		at org.wordpress.android.stores.network.xmlrpc.site.SiteXMLRPCClient.updateSiteFromOptions(SiteXMLRPCClient.java:145)
		at org.wordpress.android.stores.network.xmlrpc.site.SiteXMLRPCClient.access$200(SiteXMLRPCClient.java:27)
		at org.wordpress.android.stores.network.xmlrpc.site.SiteXMLRPCClient$3.onResponse(SiteXMLRPCClient.java:86)
		at org.wordpress.android.stores.network.xmlrpc.XMLRPCRequest.deliverResponse(XMLRPCRequest.java:53)
		at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
		at android.os.Handler.handleCallback(Handler.java:739)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at android.os.Looper.loop(Looper.java:148)
		at android.app.ActivityThread.main(ActivityThread.java:5417)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by aforcier** [comment]
Fixed in #135.
