### ISSUE TITLE
Example app crashes on API <= 22

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#816]
First reported [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/804#pullrequestreview-123236713).

> ...the app crashes on all emulators running 22 and lower and the one physical device running API 22 with the following error:

```
AndroidRuntime  E  FATAL EXCEPTION: main
               E  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android.fluxc.example/org.wordpress.android.fluxc.example.MainExampleActivity}: kotlin.Unin
                  itializedPropertyAccessException: lateinit property dispatcher has not been initialized
               E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
               E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
               E      at android.app.ActivityThread.access$600(ActivityThread.java:141)
               E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
               E      at android.os.Handler.dispatchMessage(Handler.java:99)
               E      at android.os.Looper.loop(Looper.java:137)
               E      at android.app.ActivityThread.main(ActivityThread.java:5041)
               E      at java.lang.reflect.Method.invokeNative(Native Method)
               E      at java.lang.reflect.Method.invoke(Method.java:511)
               E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
               E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
               E      at dalvik.system.NativeStart.main(Native Method)
               E  Caused by: kotlin.UninitializedPropertyAccessException: lateinit property dispatcher has not been initialized
               E      at org.wordpress.android.fluxc.example.MainFragment.onStart(MainFragment.kt:58)
               E      at android.app.Fragment.performStart(Fragment.java:1723)
               E      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:913)
               E      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
               E      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1039)
               E      at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:1845)
               E      at android.app.Activity.performStart(Activity.java:5120)
               E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
               E      ... 11 more
```

**Comment by aforcier** [comment]
The problem is that we're not using the support version of `Fragment` in the example app, and on API 22 and below we need to also implement the deprecated `onAttach(activity: Activity)` method, along with the context one (or move to support fragments, or make minSdk 23).
