### ISSUE TITLE
Instrumentation tests occasionally fail due to connection pool closing

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#92]
I see this issue occasionally, when running instrumentation tests:

```
org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
at org.wordpress.android.stores.Dispatcher.post(Dispatcher.java:46)
at org.wordpress.android.stores.Dispatcher.dispatch(Dispatcher.java:38)
at org.wordpress.android.stores.release.ReleaseStack_PostTestXMLRPC.uploadPost(ReleaseStack_PostTestXMLRPC.java:167)
at org.wordpress.android.stores.release.ReleaseStack_PostTestXMLRPC.testEditingRemotePost(ReleaseStack_PostTestXMLRPC.java:82)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
at com.yarolegovich.wellsql.SelectQuery.getAsModel(SelectQuery.java:151)
at com.yarolegovich.wellsql.SelectQuery.getAsModel(SelectQuery.java:144)
at org.wordpress.android.stores.network.HTTPAuthManager.getHTTPAuthModel(HTTPAuthManager.java:27)
at org.wordpress.android.stores.network.BaseRequest.setHTTPAuthHeaderOnMatchingURL(BaseRequest.java:33)
at org.wordpress.android.stores.network.xmlrpc.BaseXMLRPCClient.setRequestAuthParams(BaseXMLRPCClient.java:58)
at org.wordpress.android.stores.network.xmlrpc.BaseXMLRPCClient.add(BaseXMLRPCClient.java:43)
at org.wordpress.android.stores.network.xmlrpc.post.PostXMLRPCClient.pushPost(PostXMLRPCClient.java:324)
at org.wordpress.android.stores.store.PostStore.onAction(PostStore.java:319)
at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
... 20 more
```

In this case the failing test was during a post test, but I've seen it happen with other instrumentation tests. The test was dispatching a `PUSH_POST` action.

I've gone many days of running integration tests without seeing this error, and then I'll get it a few times in a row. Usually running 'Clean project' solves it, but not always.

**Comment by aforcier** [comment]
Almost certainly fixed by the concurrency changes to WellSql in #116. We'll re-open this if we run into this issue again.
