### ISSUE TITLE
NumberFormatException in WCOrderModel line item quantity

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-FluxC-Android#972]
We have one user who appears to have a [line item quantity](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCOrderModel.kt#L73) of `0.98`, which results in a crash because quantity is expected to be an int.

```
Fatal Exception: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 0.98 at line 1 column 643 path $[2].quantity
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:245)
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:235)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
       at com.google.gson.Gson.fromJson(Gson.java:887)
       at com.google.gson.Gson.fromJson(Gson.java:852)
       at com.google.gson.Gson.fromJson(Gson.java:801)
       at org.wordpress.android.fluxc.model.WCOrderModel.getLineItemList(WCOrderModel.kt:117)
       at com.woocommerce.android.ui.orders.OrderDetailProductListView.initView(OrderDetailProductListView.kt:45)
       at com.woocommerce.android.ui.orders.OrderDetailFragment.showOrderDetail(OrderDetailFragment.kt:124)
       at com.woocommerce.android.ui.orders.OrderDetailPresenter.loadOrderDetail(OrderDetailPresenter.kt:67)
```

Fabric 5bc48c99f8b88c2963e46f30

**Comment by nbradbury** [comment]
Most likely solution is to change `quantity` to a float.
